language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

script:
    - phpize
    - ./configure
    - make
    - SHOW_ONLY_GROUPS="FAIL,XFAIL,BORK,WARN,LEAK,SKIP" NO_INTERACTION=1 php -n run-tests.php -n -d extension_dir=./modules/ -d extension=memtrigger.so -p `phpenv which php` --show-diff --set-timeout 120